config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :parks, except: :destroy do
    resources :bookmarks, only: :create
    resources :reviews, only: [:new, :create, :index]
  end
  resources :bookmarks, only: [:index, :destroy]
  delete 'bookmarks/:id/d', to: 'bookmarks#destroy_fresh', as: :destroy_fresh
  resources :park_categories do
    resources :votes, only: [:create, :index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :park
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :park_categories
end

app/models/park.rb
class Park < ApplicationRecord
  REGIONS = ["Rinkeby-Kista", "Kungsholmen", "Norrmalm", "Östermalm", "Södermalm", "Hägersten-Älvsjö", "Enskede-Årsta-Vantör"]
  has_many :park_categories, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  has_many_attached :photos
  validates :name, presence: true
    include PgSearch::Model
  pg_search_scope :search_by_name_and_details,
    against: [ :name, :address, :region, :details ],
    using: {
      tsearch: { prefix: true }
    }
  validates :region, inclusion: { in: REGIONS }
  
  def get_rating
    reviews = self.reviews
    total = 0
    reviews.each do |review|
      total += review.rating
    end
    average = total / reviews.count.to_f.round(1)
    unless average.nan?
      self.rating = average
    else
      self.rating = 1.0
    end
    self.rating = 1.0 if self.rating.nil?
  end
end

app/models/park_category.rb
class ParkCategory < ApplicationRecord
  belongs_to :category
  belongs_to :park
  has_many :votes, dependent: :destroy

  def score
    self.score = self.votes.count
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :park
  validates :rating, presence: true, inclusion: { in: (1..5).to_a }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookmarks
  has_many :reviews
  has_many :votes
  has_one_attached :avatar
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :park_category
  validates :user_id, uniqueness: { scope: :park_category_id }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :avatar])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :avatar])
  end

  def default_url_options
  { host: ENV["www.parkn.club"] || "localhost:3000" }
end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def index
    @user = current_user
    @bookmarks = @user.bookmarks
  end

  def create
    @bookmark = Bookmark.new
    @park = Park.find(params[:park_id])
    @bookmark.park = @park
    @park.get_rating
    @bookmark.user = current_user

      @bookmark.save!
      if @bookmark.save!
        respond_to do |format|
          format.html
          format.json {render json: { partial: render_to_string(partial: "bookmarks/delete.html.erb") }}
        end
      end
  end

  def destroy
    if Bookmark.find(params[:id])
      @bookmark = Bookmark.find(params[:id])
      p @bookmark
    end
    if Bookmark.find(params[:id])
      @park = @bookmark.park
        @bookmark.destroy
        respond_to do |format|
          format.html
          format.json { render json: { partial: render_to_string(partial: "bookmarks/create.html.erb") } }
        end
      end
  end

  def destroy_fresh
     @bookmark = Bookmark.find(params[:id]) if Bookmark.find(params[:id])
    if Bookmark.find(params[:id])
      @park = @bookmark.park
      @bookmark.destroy
      redirect_to bookmarks_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/parks_controller.rb
class ParksController < ApplicationController
  def index
    @parks = Park.all
    @parks.each do |p|
      p.get_rating
    end
    @markers = @parks.geocoded.map do |park|
      {
        lat: park.latitude,
        lng: park.longitude,
        info_window: render_to_string(partial: "info_window", locals: { park: park })
      }
    end
    if params[:query].present?
      @parks = @parks.search_by_name_and_details(params[:query])
      @parks.each do |p|
        p.get_rating
      end
      @markers = @parks.geocoded.map do |park|
      {
        lat: park.latitude,
        lng: park.longitude,
        info_window: render_to_string(partial: "info_window", locals: { park: park })
      }
      end
      @parks = @parks.sort_by(&:rating).reverse
    else
      @parks = @parks.sort_by(&:rating).reverse
    end
  end

  def show
    @review = Review.new
    @park = Park.find(params[:id])
    @reviews = @park.reviews
    @park_categories = ParkCategory.where(park_id: @park.id)
    @park_categories.each do |pc|
      pc.score
    end
    @park_arr = []
    @park_arr << @park
    @markers = @park_arr.map do |park|
      {
        lat: park.latitude.nil? ? 59.3354662 : park.latitude,
        lng: park.longitude.nil? ? 18.0600026 : park.longitude,
        info_window: render_to_string(partial: "info_window", locals: { park: park })
      }
    end
    @favorite = is_favorite?(@park.id)
    @park.get_rating
    @user = current_user
  end

  def new
    @park = Park.new
  end

  def create
    @park = Park.new(park_params)
    if @park.save
      redirect_to park_path(@park)
    else
      render :new
    end
    Category.all.each do |category|
      ParkCategory.create(category_id: category.id, park_id: @park.id)
    end
  end

  def edit
    @park = Park.find(params[:id])
  end

  def update
    @park = Park.find(params[:id])
    @park.update(park_params)
    redirect_to park_path(@park)
  end

  private

  def park_params
    params.require(:park).permit(:name, :address, :region, :details, photos: [])
  end

  def is_favorite?(id)
    @user = current_user
    @bookmark = @user.bookmarks.where(:park_id => id).last
    return @bookmark.present?
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
    @park = Park.find(params[:park_id])
    @review.park = @park
  end

  def create
    @review = Review.new(review_params)
    @park = Park.find(params[:park_id])
    @review.park = @park
    @review.user = current_user
    @park.get_rating
    @review.save
    redirect_to park_path(@park)
  end

  private

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def index
    @votes = Votes.all
  end

  def create
    @vote = Vote.new
    @park_category = ParkCategory.find(params[:park_category_id])
    @vote.park_category = @park_category
    @vote.user = current_user
    @vote.save
    respond_to do |format|
      format.html
      format.json { render json: { counter: @park_category.votes.count } }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/bookmarks/_create.html.erb
<i class="far fa-heart empty-heart" data-action="click->like#create"></i>

app/views/bookmarks/_delete.html.erb
<i class="fas fa-heart full-heart" data-action="click->like#delete"  data-bookmark="<%= @bookmark.id %>"></i>

app/views/bookmarks/index.html.erb
<div class="items d-flex">
    <div class="card-fav">
      <% if current_user.avatar.attached? %>
        <%= cl_image_tag current_user.avatar.key, class: "avatar-bookmark" %>
      <% else %>
        <%= image_tag "https://i.pravatar.cc/150?img=13", class: "avatar-bookmark" %>
      <% end %>
      <h1> <%= current_user.first_name.capitalize %> <%= current_user.last_name.capitalize %> </h1>
      <p class="title">My favorite parks</p>
      <p id="leaf-black">By <i class="fas fa-leaf leaf-black"></i> ParkN</p>
    </div>
    <div class="cards-index fav-park">
      <% @bookmarks.each do |bookmark| %>
        <div class="card-park card-park-fav">
          <% if bookmark.park.photos.attached? %>
            <%= cl_image_tag bookmark.park.photos.first.key %>
          <% else %>
            <%= cl_image_tag bookmark.park.key %>
          <% end %>
          <div class="card-park-infos">
            <% bookmark.park.get_rating %>
            <% @rating = bookmark.park.rating %>
            <%= render 'parks/rating' %>
            <div>
              <%=link_to bookmark.park.name, park_path(bookmark.park) %>
            </div>
             <div>
                  <%= link_to "bookmarks/#{bookmark.id}/d", method: :delete, data: { confirm: "Remove from favorites?" } do %>
                    <i class="fas full-heart fa-heart heart"></i>
                <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />
    <meta property="fb:app_id" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Overlock:wght@400;700&display=swap" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= favicon_link_tag %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/offers/show.html.erb
<!-- app/views/offers/show.html.erb -->
<% content_for :meta_title, "#{@offer.name} is on #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, @offer.description %>
<% content_for :meta_image, cl_image_path(@offer.photo.path) %>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url( <%= image_path "park1.jpg" %>);">
  <div class="home-container" style="">
    <h1><strong class="til">ParkN</strong> gives you park information with just a click!</h1>
    <p>Make your park visits more fun.</p>
    <%= form_tag parks_path, method: :get do %>
       <div class="d-flex search_bar">
        <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          placeholder: "Find a park"
        %>
       <%= submit_tag "Search", class: "btn btn-flat" %>
    <% end %>
    </div>
  </div>
</div>

app/views/parks/_emoji.html.erb
<div class="emoji-cards">
  <% @park_categories.sort_by(&:score).reverse.each do |park_category| %>
    <%= link_to '#', class: 'emoji-button', method: :post, remote: true, data: { controller: "counter", action: "click->counter#refresh"} do %>
      <% if current_user.votes.where(:park_category_id => park_category.id).empty? %>
        <div class="emoji-card" data-counter-target="button">
      <% else %>
        <div class="emoji-card-clicked">
      <% end %>
      <h3 class="emoji">
        <i class="fas fa-<%= park_category.category.emoji %>" title="<%= park_category.category.name.capitalize %>"></i>
      </h3>
      <div class="line"></div>
      <h3 class="counter" data-counter-target="count" data-category="<%= park_category.id %>" ><%= park_category.votes.count %></h3>
      </div>
    <% end %>
  <% end %>
</div>

app/views/parks/_info_window.html.erb
<h3><%= link_to park.name, park_path(park) %></h3>

app/views/parks/_rating.html.erb
<div class="rating">
  <i class="fas fa-star"></i>
  <% if @rating < 1.5 %>
    <i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i>
  <% elsif @rating < 2 %>
    <i class="fas fa-star-half-alt"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i>
  <% elsif @rating < 2.5 %>
    <i class="fas fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i>
  <% elsif @rating < 3 %>
    <i class="fas fa-star"></i><i class="fas fa-star-half-alt"></i><i class="far fa-star"></i><i class="far fa-star"></i>
  <% elsif @rating < 3.5 %>
    <i class="fas fa-star"></i><i class="fas fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i>
  <% elsif @rating < 4 %>
    <i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star-half-alt"></i><i class="far fa-star"></i>
  <% elsif @rating < 4.5 %>
    <i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="far fa-star"></i>
  <% elsif @rating < 5.0 %>
    <i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star-half-alt"></i>
  <% elsif @rating == 5.0 %>
    <i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i>
  <% else %>
    <i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i>
  <% end %>
</div>

app/views/parks/edit.html.erb
<div id="img-back"style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url( <%= image_path "park1.jpg" %>);">
  <div id="create" class="container create-form col-8 col-offset-5 mt-5 bg-white py-5 px-5">
    <div id="create-form">
      <h2 id="form-title">edit a park</h2>
          <%= simple_form_for(@park) do |f| %>
            <%= f.input :name %>
            <%= f.input :address %>
            <%= f.input :region, :as => :select, :collection => Park::REGIONS %>
            <%= f.input :details %>
            <%= f.input :photos, as: :file, input_html: { multiple: true } %>
            <%= f.submit class: "btn btn-success w-100" %>
          <% end %>
    </div>
  </div>
</div>

app/views/parks/index.html.erb
<div class="show-container">
  <div class="container">
    <div class="srch">
      <%= render 'shared/search' %>
      <div class="search-bar"></div>
    </div>
    <div class="cards-index">
      <% @parks.each do |park| %>
        <%= link_to park_path(park) do %>
          <div class="card-park">
            <% if park.photos.attached? %>
              <%= cl_image_tag park.photos.first.key %>
            <% else %>
              <%= cl_image_tag park.key %>
            <% end %>
              <div class="card-park-infos">
                <% park.get_rating %>
                <% @rating = park.rating %>
                <%= render 'rating' %>
                <h2><%= park.name %></h2>
                <p class="card-park-region"> <%= park.region %></p>
              </div>
           </div>
        <% end %>
      <% end %>
    </div>
  </div>
  <div id="map"
     style="width: 100%; height: 600px;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

app/views/parks/new.html.erb
<div id="img-back"style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url( <%= image_path "park1.jpg" %>);">
  <div id="create" class="container create-form col-8 col-offset-5 mt-5 bg-white py-5 px-5">
    <div id="create-form">
      <h2 id="form-title">Add a park</h2>
      <%= simple_form_for(@park) do |f| %>
        <%= f.input :name %>
        <%= f.input :address %>
        <%= f.input :region, :as => :select, :collection => Park::REGIONS %>
        <%= f.input :details %>
        <%= f.input :photos, as: :file, input_html: { multiple: true } %>
        <%= f.submit class: "btn btn-success w-100" %>
      <% end %>
    </div>
  </div>
</div>

app/views/parks/show.html.erb
<div class="container text-center pt-3">
  <h1><%= @park.name %></h1>
</div>
  <div class="show-container">
    <div>
    <div class="card-show">
      <% if @park.photos.attached? %>
        <%= cl_image_tag @park.photos.first.key %>
      <% else %>
        <%= cl_image_tag @park.key %>
      <% end %>
      <div class="card-show-infos">
        <div data-controller="like" data-like-target="link" data-park="<%= @park.id %>" data-bookmark="<%= Bookmark.find_by(user: current_user, park: @park).id if Bookmark.find_by(user: current_user, park: @park)%>">
          <% unless @favorite %>
              <i class="far fa-heart empty-heart" data-action="click->like#create"></i>
          <% else %>
              <i class="fas fa-heart full-heart" data-action="click->like#delete"  data-bookmark="<%= @bookmark.id %>"></i>
          <% end %>
        </div>
        <% @rating = @park.rating %>
        <%= render 'rating' %>
        <%= render 'emoji' %>
        <div>
          <h3><%= @park.details %></h3>
          <button type="button" class="btn btn-success" data-toggle="modal" data-target="#exampleModal">Add a review</button>
          <%= render 'reviews/modal' %>
        </div>
      </div>
    </div>
    <div class="review-container">
      <h1>Reviews</h1>
      <% @reviews.reverse.each do |review| %>
        <div class="card-review">
          <div class="review-rating">
            <i class="fas fa-star"></i>
            <% @rating = review.rating %>
            <% if @rating < 1.5 %>
              <i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i>
            <% elsif @rating < 2.5 %>
              <i class="fas fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i>
            <% elsif @rating < 3.5 %>
              <i class="fas fa-star"></i><i class="fas fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i>
            <% elsif @rating < 4.5 %>
              <i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="far fa-star"></i>
            <% elsif @rating == 5.0 %>
              <i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i>
            <% else %>
              <i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i>
            <% end %>
          </div>
          <div class="avatar-img">
            <% if review.user.avatar.attached? %>
              <%= cl_image_tag review.user.avatar.key, class: "avatar-review" %>
            <% else %>
              <%= image_tag "https://i.pravatar.cc/150?img=13", class: "avatar-review" %>
            <% end %>
          </div>
          <div class="card-review-text">
            <span id="review-name"> <%= review.user.first_name.capitalize %> <%= review.user.last_name.capitalize %> </span>
            <span id="review-time"> <%= review.created_at.strftime("%a %b %e") %> </span>
            <p> <%= review.content %> </p>
          </div>
        </div>

      <% end %>
    </div>
  </div>
  <div id="map"
     style="width: 100%; height: 600px;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

app/views/reviews/_modal.html.erb
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title w-100 text-center" id="exampleModalLabel"><%= @park.name %></h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= simple_form_for [@park, @review] do |f| %>
          <%= f.input :rating, collection: (1..5).to_a, label:false %>
          <%= f.input :content, label: "My review:" %>
          <%= f.submit "Submit", class: "btn btn-success w-100" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer d-flex justify-content-between align-items-center">
  <div class="footer-copyright">
    <i class="fab fa-facebook-square"></i>
    <i class="fab fa-instagram-square"></i>
    <i class="fab fa-twitter-square"></i>
    <i class="fas fa-envelope-square"></i>
  </div>
    <div class="d-flex justify-content-right align-items-center">
      <p id="footer-right"><i class="fas fa-leaf"></i> ParkN</p>
    </div>
</div>

app/views/shared/_navbar.html.erb
<style>
  @import url('https://fonts.googleapis.com/css2?family=Amatic+SC&display=swap');
</style>

<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "/", class: "navbar-brand" do %>
    <h1 class="parkn">Park<strong>N</strong></h1>
  <% end %>
  <button class="navbar-toggler mobile-hide" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon mobile-hide"></span>
  </button>
  <div class="collapse navbar-collapse mobile-hide" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto mobile-hide">
      <% if user_signed_in? %>
        <li class="nav-item mobile-hide">
          <%= link_to "Explore", parks_path, class: "nav-link un" %>
        </li>
        <li class="nav-item dropdown mobile-hide">
          <% if current_user.avatar.attached? %>
            <%= cl_image_tag current_user.avatar.key, class: "avatar dropdown-toggle mobile-hide", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%= cl_image_tag "default_avatar", class: "avatar dropdown-toggle mobile-hide", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right mobile-hide" aria-labelledby="navbarDropdown">
            <%= link_to "Add a park", new_park_path, class: "dropdown-item mobile-hide" %>
            <%= link_to "My Parks", bookmarks_path(@bokmarks), class: "dropdown-item mobile-hide" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item mobile-hide" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item mobile-hide">
          <%= link_to "Login", new_user_session_path, class: "nav-link mobile-hide" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_search.html.erb
<div class="search-bar">
  <%= form_tag parks_path, method: :get do %>
  <div class="d-flex search_bar">
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Find a park"
      %>
   <%= submit_tag "Search", class: "btn btn-primary" %></div>
  <% end %>
</div>